"""GMAT reference workflow for M1 (DR-0005, ADR-0006).

- ``m1_script`` deterministically generates the GMAT script from the scenario, so
  the reference configuration cannot silently drift from ours.
- ``parse_report`` reads GMAT's ReportFile output.
- ``compare`` measures three differences so a discrepancy can be attributed:
    ours vs GMAT, GMAT vs exact Kepler, ours vs exact Kepler.
  If ours-vs-GMAT ~ ours-vs-Kepler and GMAT-vs-Kepler is much smaller, the
  difference is our (RK4) numerical error, not a modelling disagreement.

GMAT works in km and km/s; conversion happens only here (ADR-0002).
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass

import numpy as np

from tars.astro import kepler
from tars.astro.elements import keplerian_period, specific_energy
from tars.sim.runner import initial_state
from tars.sim.scenario import Scenario
from tars.sim.state import StateSnapshot

REPORT_COLUMNS = (
    "ElapsedS",
    "Sat.TTModJulian",
    "Sat.EarthMJ2000Eq.X",
    "Sat.EarthMJ2000Eq.Y",
    "Sat.EarthMJ2000Eq.Z",
    "Sat.EarthMJ2000Eq.VX",
    "Sat.EarthMJ2000Eq.VY",
    "Sat.EarthMJ2000Eq.VZ",
    "Sat.Earth.SMA",
    "Sat.Earth.ECC",
    "Sat.EarthMJ2000Eq.INC",
    "Sat.Earth.OrbitPeriod",
)
_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _gmat_epoch(iso: str) -> str:
    """'2026-01-01T00:00:00' -> GMAT Gregorian '01 Jan 2026 00:00:00.000'."""
    date, time = iso.split("T")
    year, month, day = date.split("-")
    hh, mm, ss = time.split(":")
    return f"{int(day):02d} {_MONTHS[int(month) - 1]} {year} {hh}:{mm}:{float(ss):06.3f}"


def report_schedule(scenario: Scenario) -> tuple[float, int]:
    """Report interval [s] and count matching our telemetry samples up to the last full one."""
    c = scenario.constants
    period = keplerian_period(c.equatorial_radius + scenario.initial_orbit.altitude_m, c.mu)
    interval = scenario.telemetry.sample_interval_s
    return interval, math.floor(scenario.stop.orbits * period / interval)


def m1_script(scenario: Scenario, report_path: str = "m1_two_body_report.txt") -> str:
    """GMAT script reproducing the scenario: point-mass Earth, WGS 84 constants, same state."""
    if scenario.force_models != ("point_mass_gravity",):
        raise ValueError("M1 GMAT script supports point-mass gravity only (DR-0002)")
    c = scenario.constants
    r0, v0 = initial_state(scenario)
    # Plain Python floats: repr() is the shortest exact round-trip decimal form.
    r_km = [float(x) / 1000.0 for x in r0]
    v_kms = [float(x) / 1000.0 for x in v0]
    interval, count = report_schedule(scenario)
    report = " ".join(REPORT_COLUMNS)
    return f"""%% M1 two-body reference case for GMAT R2026a.
%% GENERATED by toolbox/scripts/gmat_m1.py from scenario '{scenario.name}' -- do not edit.
%% scenario_hash: {scenario.config_hash()}
%% Model: point-mass Earth only (SCI-0001, SCI-0004); constants {c.name} (SCI-0005).

%----- Earth constants overridden to match the project (DR-0003). GMAT default Mu is
%----- 398600.4415 km^3/s^2; point-mass forces use the body's Mu.
GMAT Earth.Mu = {c.mu / 1e9!r};
GMAT Earth.EquatorialRadius = {c.equatorial_radius / 1000.0!r};

Create Spacecraft Sat;
GMAT Sat.DateFormat = TTGregorian;
GMAT Sat.Epoch = '{_gmat_epoch(scenario.epoch)}';
GMAT Sat.CoordinateSystem = EarthMJ2000Eq;
GMAT Sat.DisplayStateType = Cartesian;
GMAT Sat.X = {r_km[0]!r};
GMAT Sat.Y = {r_km[1]!r};
GMAT Sat.Z = {r_km[2]!r};
GMAT Sat.VX = {v_kms[0]!r};
GMAT Sat.VY = {v_kms[1]!r};
GMAT Sat.VZ = {v_kms[2]!r};

Create ForceModel TwoBodyFM;
GMAT TwoBodyFM.CentralBody = Earth;
GMAT TwoBodyFM.PrimaryBodies = {{}};
GMAT TwoBodyFM.PointMasses = {{Earth}};
GMAT TwoBodyFM.Drag = None;
GMAT TwoBodyFM.SRP = Off;
GMAT TwoBodyFM.RelativisticCorrection = Off;
GMAT TwoBodyFM.ErrorControl = RSSStep;

%----- High-accuracy adaptive integrator: GMAT is the reference, not a copy of our RK4.
Create Propagator TwoBodyProp;
GMAT TwoBodyProp.FM = TwoBodyFM;
GMAT TwoBodyProp.Type = PrinceDormand78;
GMAT TwoBodyProp.InitialStepSize = {interval!r};
GMAT TwoBodyProp.Accuracy = 1e-13;
GMAT TwoBodyProp.MinStep = 0;
GMAT TwoBodyProp.MaxStep = {interval!r};
GMAT TwoBodyProp.MaxStepAttempts = 50;
GMAT TwoBodyProp.StopIfAccuracyIsViolated = true;

Create ReportFile M1Report;
GMAT M1Report.Filename = '{report_path}';
GMAT M1Report.Precision = 16;
GMAT M1Report.WriteHeaders = true;
GMAT M1Report.LeftJustify = On;
GMAT M1Report.ZeroFill = Off;
GMAT M1Report.FixedWidth = true;
GMAT M1Report.Delimiter = ' ';
GMAT M1Report.ColumnWidth = 28;
GMAT M1Report.WriteReport = true;

Create Variable I ElapsedS;

BeginMissionSequence;
ElapsedS = 0;
Report M1Report {report};
For I = 1:{count};
   Propagate TwoBodyProp(Sat) {{Sat.ElapsedSecs = {interval!r}}};
   ElapsedS = {interval!r} * I;
   Report M1Report {report};
EndFor;
"""


@dataclass(frozen=True)
class GmatRow:
    t: float
    r: np.ndarray  # m
    v: np.ndarray  # m/s
    sma: float  # m
    ecc: float
    inc_deg: float
    period: float  # s


def parse_report(text: str) -> list[GmatRow]:
    lines = [line for line in text.splitlines() if line.strip()]
    header = lines[0].split()
    if tuple(header) != REPORT_COLUMNS:
        raise ValueError(f"unexpected GMAT report columns: {header}")
    rows = []
    for line in lines[1:]:
        if line.split() == header:
            continue  # GMAT repeats the header when the first in-loop Report executes
        f = [float(x) for x in line.split()]
        rows.append(
            GmatRow(
                t=f[0],
                r=np.array(f[2:5]) * 1000.0,
                v=np.array(f[5:8]) * 1000.0,
                sma=f[8] * 1000.0,
                ecc=f[9],
                inc_deg=f[10],
                period=f[11],
            )
        )
    return rows


def compare(
    rows: Sequence[GmatRow], samples: Sequence[StateSnapshot], scenario: Scenario
) -> dict[str, float]:
    mu = scenario.constants.mu
    interval, count = report_schedule(scenario)
    expected_times = [interval * k for k in range(count + 1)]
    if [row.t for row in rows] != expected_times:
        # A truncated or re-gridded reference must never pass (REV-002).
        raise ValueError(
            f"incomplete GMAT reference: {len(rows)} rows, expected {count + 1} "
            f"at {interval} s spacing up to {expected_times[-1]} s"
        )
    ours = {s.t: s for s in samples}
    missing = [row.t for row in rows if row.t not in ours]
    if missing:
        raise ValueError(f"GMAT report times not on our sample grid: {missing[:5]}")
    initial = samples[0]

    def err(a: np.ndarray, b: np.ndarray) -> float:
        return float(np.linalg.norm(a - b))

    ours_gmat_r, ours_gmat_v, gmat_kep_r, gmat_kep_v, ours_kep_r = [], [], [], [], []
    for row in rows:
        s = ours[row.t]
        r_k, v_k = kepler.propagate(initial.r, initial.v, row.t - initial.t, mu)
        ours_gmat_r.append(err(s.r, row.r))
        ours_gmat_v.append(err(s.v, row.v))
        gmat_kep_r.append(err(row.r, r_k))
        gmat_kep_v.append(err(row.v, v_k))
        ours_kep_r.append(err(s.r, r_k))

    a_expected = -mu / (2.0 * specific_energy(initial.r, initial.v, mu))
    return {
        "position_error_max_m": max(ours_gmat_r),
        "velocity_error_max_mps": max(ours_gmat_v),
        "gmat_vs_kepler_position_error_max_m": max(gmat_kep_r),
        "gmat_vs_kepler_velocity_error_max_mps": max(gmat_kep_v),
        "ours_vs_kepler_position_error_max_m": max(ours_kep_r),
        # Constant-match check (SCI-0005): GMAT's initial SMA uses its own Mu.
        "initial_sma_difference_m": abs(rows[0].sma - a_expected),
        "initial_state_difference_m": err(rows[0].r, initial.r),
        "period_difference_s": abs(rows[0].period - keplerian_period(a_expected, mu)),
        "rows_compared": float(len(rows)),
    }


def provenance_problems(metadata: dict, scenario: Scenario, committed_script: str) -> list[str]:
    """Exact (tolerance-free) checks that the committed reference matches the project (REV-001).

    The committed script must equal the script regenerated from the current scenario
    (so its Earth.Mu / EquatorialRadius lines carry the current constants), and the
    recorded constants must equal the scenario's constants.
    """
    problems = []
    if metadata.get("scenario_hash") != scenario.config_hash():
        problems.append("scenario hash differs (stale reference)")
    if committed_script != m1_script(scenario):
        problems.append("committed GMAT script differs from the script generated for this scenario")
    c = scenario.constants
    expected = {
        "name": c.name,
        "mu_km3_s2": c.mu / 1e9,
        "equatorial_radius_km": c.equatorial_radius / 1000.0,
    }
    if metadata.get("constants") != expected:
        problems.append(f"metadata constants {metadata.get('constants')} != {expected}")
    return problems
