"""Informational GMAT runs with a realistic force model (DR-0005; not an M1 gate).

Measures how far the approved M1 model (point-mass Earth, no drag; SCI-0001, SCI-0004)
departs from a higher-fidelity model over the same 10 orbits, starting from the same
Cartesian state. Cases isolate each effect:

- j2_only:        JGM-3 degree 2, order 0 (oblateness only)
- gravity_4x4:    JGM-3 4x4
- realistic_fNNN: JGM-3 4x4 + Jacchia-Roberts drag at constant F10.7 = NNN

Spacecraft drag properties are GMAT's default spacecraft (850 kg, 15 m^2, Cd 2.2), used
as an illustrative ballistic coefficient because the project has not yet defined a
spacecraft. Results are model sensitivities, not predictions for a specific vehicle.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass

import numpy as np

from tars.astro.elements import keplerian_period
from tars.sim.constants import EARTH_J2_APPROX
from tars.sim.runner import initial_state
from tars.sim.scenario import Scenario
from tars.sim.state import StateSnapshot
from tars.validation.gmat import _gmat_epoch, report_schedule

REPORT_COLUMNS = (
    "ElapsedS",
    "Sat.EarthMJ2000Eq.X",
    "Sat.EarthMJ2000Eq.Y",
    "Sat.EarthMJ2000Eq.Z",
    "Sat.EarthMJ2000Eq.VX",
    "Sat.EarthMJ2000Eq.VY",
    "Sat.EarthMJ2000Eq.VZ",
    "Sat.Earth.SMA",
    "Sat.Earth.ECC",
    "Sat.EarthMJ2000Eq.INC",
    "Sat.EarthMJ2000Eq.RAAN",
    "Sat.Earth.Altitude",
)

# Illustrative spacecraft: GMAT's default spacecraft values (see module docstring).
SPACECRAFT = {"DryMass": 850.0, "DragArea": 15.0, "Cd": 2.2}


@dataclass(frozen=True)
class Case:
    name: str
    degree: int
    order: int
    drag: bool
    f107: float | None = None
    kp: float = 3.0  # GMAT default constant geomagnetic index


CASES = (
    Case("j2_only", 2, 0, False),
    Case("gravity_4x4", 4, 4, False),
    Case("realistic_f70", 4, 4, True, 70.0),
    Case("realistic_f150", 4, 4, True, 150.0),
    Case("realistic_f250", 4, 4, True, 250.0),
)


def realistic_script(scenario: Scenario, case: Case, report_path: str) -> str:
    c = scenario.constants
    r0, v0 = initial_state(scenario)
    r_km = [float(x) / 1000.0 for x in r0]
    v_kms = [float(x) / 1000.0 for x in v0]
    interval, count = report_schedule(scenario)
    report = " ".join(REPORT_COLUMNS)
    if case.drag:
        drag = f"""GMAT FM.Drag.AtmosphereModel = JacchiaRoberts;
GMAT FM.Drag.HistoricWeatherSource = 'ConstantFluxAndGeoMag';
GMAT FM.Drag.PredictedWeatherSource = 'ConstantFluxAndGeoMag';
GMAT FM.Drag.F107 = {case.f107!r};
GMAT FM.Drag.F107A = {case.f107!r};
GMAT FM.Drag.MagneticIndex = {case.kp!r};"""
    else:
        drag = "GMAT FM.Drag = None;"
    return f"""%% INFORMATIONAL realistic-model case '{case.name}' (DR-0005). NOT an M1 gate.
%% GENERATED by toolbox/scripts/gmat_m1.py from scenario '{scenario.name}' -- do not edit.
%% scenario_hash: {scenario.config_hash()}

GMAT Earth.Mu = {c.mu / 1e9!r};
GMAT Earth.EquatorialRadius = {c.equatorial_radius / 1000.0!r};

Create Spacecraft Sat;
GMAT Sat.DateFormat = TTGregorian;
GMAT Sat.Epoch = '{_gmat_epoch(scenario.epoch)}';
GMAT Sat.CoordinateSystem = EarthMJ2000Eq;
GMAT Sat.DisplayStateType = Cartesian;
GMAT Sat.X = {r_km[0]!r};
GMAT Sat.Y = {r_km[1]!r};
GMAT Sat.Z = {r_km[2]!r};
GMAT Sat.VX = {v_kms[0]!r};
GMAT Sat.VY = {v_kms[1]!r};
GMAT Sat.VZ = {v_kms[2]!r};
GMAT Sat.DryMass = {SPACECRAFT["DryMass"]!r};
GMAT Sat.DragArea = {SPACECRAFT["DragArea"]!r};
GMAT Sat.Cd = {SPACECRAFT["Cd"]!r};

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PrimaryBodies = {{Earth}};
GMAT FM.PointMasses = {{}};
GMAT FM.GravityField.Earth.Degree = {case.degree};
GMAT FM.GravityField.Earth.Order = {case.order};
GMAT FM.GravityField.Earth.PotentialFile = 'JGM3.cof';
GMAT FM.GravityField.Earth.TideModel = 'None';
GMAT FM.SRP = Off;
GMAT FM.RelativisticCorrection = Off;
GMAT FM.ErrorControl = RSSStep;
{drag}

Create Propagator Prop;
GMAT Prop.FM = FM;
GMAT Prop.Type = PrinceDormand78;
GMAT Prop.InitialStepSize = {interval!r};
GMAT Prop.Accuracy = 1e-12;
GMAT Prop.MinStep = 0;
GMAT Prop.MaxStep = {interval!r};
GMAT Prop.MaxStepAttempts = 50;

Create ReportFile R;
GMAT R.Filename = '{report_path}';
GMAT R.Precision = 16;
GMAT R.WriteHeaders = true;
GMAT R.LeftJustify = On;
GMAT R.ZeroFill = Off;
GMAT R.FixedWidth = true;
GMAT R.Delimiter = ' ';
GMAT R.ColumnWidth = 28;

Create Variable I ElapsedS;

BeginMissionSequence;
ElapsedS = 0;
Report R {report};
For I = 1:{count};
   Propagate Prop(Sat) {{Sat.ElapsedSecs = {interval!r}}};
   ElapsedS = {interval!r} * I;
   Report R {report};
EndFor;
"""


@dataclass(frozen=True)
class Row:
    t: float
    r: np.ndarray  # m
    v: np.ndarray  # m/s
    sma: float  # m
    ecc: float
    inc_deg: float
    raan_deg: float
    altitude: float  # m, GMAT geodetic altitude above the ellipsoid


def parse_report(text: str) -> list[Row]:
    lines = [line for line in text.splitlines() if line.strip()]
    header = lines[0].split()
    if tuple(header) != REPORT_COLUMNS:
        raise ValueError(f"unexpected report columns: {header}")
    rows = []
    for line in lines[1:]:
        if line.split() == header:
            continue
        f = [float(x) for x in line.split()]
        rows.append(
            Row(
                t=f[0],
                r=np.array(f[1:4]) * 1000.0,
                v=np.array(f[4:7]) * 1000.0,
                sma=f[7] * 1000.0,
                ecc=f[8],
                inc_deg=f[9],
                raan_deg=f[10],
                altitude=f[11] * 1000.0,
            )
        )
    return rows


def ric(delta_r: np.ndarray, r: np.ndarray, v: np.ndarray) -> tuple[float, float, float]:
    """Radial, in-track, cross-track components of ``delta_r`` in the frame of (r, v)."""
    r_hat = r / np.linalg.norm(r)
    c_hat = np.cross(r, v)
    c_hat = c_hat / np.linalg.norm(c_hat)
    i_hat = np.cross(c_hat, r_hat)
    return float(delta_r @ r_hat), float(delta_r @ i_hat), float(delta_r @ c_hat)


def analytic_j2_raan_rate_deg_per_day(a: float, i_deg: float, mu: float, re: float) -> float:
    """First-order secular node rate for a circular orbit: -1.5 n J2 (Re/a)^2 cos i.

    J2 = 1.0826e-3 as in SCI-0001 (Vallado 2013 §9.6; Curtis 2014 §4.7).
    """
    j2 = EARTH_J2_APPROX
    n = 2.0 * math.pi / keplerian_period(a, mu)
    return math.degrees(-1.5 * n * j2 * (re / a) ** 2 * math.cos(math.radians(i_deg))) * 86400.0


def divergence(
    rows: Sequence[Row], samples: Sequence[StateSnapshot], scenario: Scenario
) -> dict[str, float]:
    """Divergence of the realistic GMAT trajectory from our M1 trajectory."""
    ours = {s.t: s for s in samples}
    c = scenario.constants
    a0 = c.equatorial_radius + scenario.initial_orbit.altitude_m
    period = keplerian_period(a0, c.mu)
    dists = []
    for row in rows:
        s = ours[row.t]
        dists.append(float(np.linalg.norm(row.r - s.r)))
    last = rows[-1]
    s_last = ours[last.t]
    rad, intr, cross = ric(last.r - s_last.r, s_last.r, s_last.v)

    t = np.array([row.t for row in rows])
    raan = np.unwrap(np.radians([row.raan_deg for row in rows]))
    raan_rate = math.degrees(np.polyfit(t, raan, 1)[0]) * 86400.0
    sma = np.array([row.sma for row in rows])
    first = sma[t < period].mean()
    last_orbit = sma[t >= t[-1] - period].mean()
    alt = np.array([row.altitude for row in rows])
    return {
        "position_divergence_max_m": max(dists),
        "position_divergence_final_m": dists[-1],
        "final_radial_m": rad,
        "final_in_track_m": intr,
        "final_cross_track_m": cross,
        "raan_rate_fit_deg_per_day": raan_rate,
        "raan_change_deg": math.degrees(raan[-1] - raan[0]),
        "analytic_j2_raan_rate_deg_per_day": analytic_j2_raan_rate_deg_per_day(
            a0, scenario.initial_orbit.inclination_deg, c.mu, c.equatorial_radius
        ),
        "mean_sma_change_first_to_last_orbit_m": float(last_orbit - first),
        "geodetic_altitude_min_m": float(alt.min()),
        "geodetic_altitude_max_m": float(alt.max()),
        "span_s": float(t[-1]),
    }
